// <auto-generated />
using System;
using FlashTuna.Core.Storage.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlashTuna.Core.Migrations
{
    [DbContext(typeof(FlashTunaDbContext))]
    [Migration("20181201085534_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("FlashTuna.Core.Common.PerfomanceMetrics.OperationMetric.OperationMetricResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClassName");

                    b.Property<string>("MethodName");

                    b.Property<int>("MetricResultStatus");

                    b.Property<double?>("Milliseconds");

                    b.Property<string>("ModuleName");

                    b.Property<DateTime?>("StartTimePoint");

                    b.Property<string>("Tag");

                    b.Property<DateTime>("TimePoint");

                    b.HasKey("Id");

                    b.ToTable("OperationMetricResults");
                });
#pragma warning restore 612, 618
        }
    }
}
