// <auto-generated />
using System;
using FlashTuna.Core.Storage.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlashTuna.Core.Migrations
{
    [DbContext(typeof(FlashTunaDbContext))]
    partial class FlashTunaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("FlashTuna.Core.Common.PerfomanceMetrics.OperationMetric.OperationMetricResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CallId");

                    b.Property<string>("ClassName");

                    b.Property<string>("MethodName");

                    b.Property<int>("MetricResultStatus");

                    b.Property<double?>("Milliseconds");

                    b.Property<string>("ModuleName");

                    b.Property<string>("Tag");

                    b.Property<DateTime>("TimePoint");

                    b.HasKey("Id");

                    b.ToTable("OperationMetricResults");
                });
#pragma warning restore 612, 618
        }
    }
}
